### ISSUE TITLE
How can we help improve the extension?

### ISSUE THREAD

**Issue by photex** [dgriffen/rls-vs2017#21]
Howdy!

Currently this extension holds a lot of promise and hope :D . There are some things that make it generally hard to use compared to other editors/ides with Rust support.

- Performance:
    There is a noticeable lag between input to the editor and the response which leads to major editing 
    difficulty. I haven't tested this on projects of comparative sizes to figure how it differs by project size or 
    complexity. It seems that per-edit the buffer is being re-evaluated synchronously. It isn't clear to me as 
    somebody new to visual studio whether that is caused by this extension or just the way the language 
    server protocol has been implemented in visual studio in general.

- Impacts to common editing features:
    The extension gives me fantastic completion options, but clicking on one, or hitting tab do not actually 
    trigger the completion. The default completion options are not accurate but tend to work as expected.
    It also isn't clear if the problem lies in visual studio or the extension. 

For me personally, completions are less of a problem than the latency issues. I created this issue to just start the conversation about what we can do to help improve things as users.

**Comment by dgriffen** [comment]
Hi @photex! Both of the issues you have described are issues with the underlying LSP implementation in VS. Completion used to work before something changed in the RLS and exercised the specification in a way that VS did not originally anticipate. The performance issues are also likely due to some parts of the VS API being inherently synchronous. If you could would you be able to download the [VS 2019 RC](https://visualstudio.microsoft.com/downloads/) and see if the issues you have noticed still persist there?

**Comment by photex** [comment]
@dgriffen Everything works really great in VS2019! I guess I'm now looking forward to April 2nd ;)

Cheers!
